### ISSUE TITLE
RDP: Delete /var/run/xrdp/xrdp.pid during container startup.

### ISSUE THREAD

**Issue by gargomoma** [scottyhardy/docker-wine#104]
First of all, thank you for your project, it's helping me a lot.

**Description:**
I'm running the container on a headless computer, and I recur to rdp to run the apps remotely.
But, I just found out that after restarting the container I cannot connect to RDP unless I remove the file mentioned above.

On the container log it shows:

> It looks like xrdp is already running.
> If not, delete /var/run/xrdp/xrdp.pid and try again.

**Solution:**
Add **rm /var/run/xrdp/xrdp.pid** at startup. 

Not a pro at docker, but I think it can be implemented in **entrypoint.sh**, same way as: 
> [rm /var/run/xrdp/xrdp-sesman.pid](https://github.com/scottyhardy/docker-wine/blob/4c6492f74129e06cf1a95a7ee1fd0e4b8f7ae05b/entrypoint.sh#L102)

Could it be possible?
Thanks again =)

**Comment by scottyhardy** [comment]
Done :)
