### ISSUE TITLE
How to became sudo user in this container?

### ISSUE THREAD

**Issue by vilija19** [scottyhardy/docker-wine#116]
How to became a sudo user in this container?
Are there any ways?

**Comment by scottyhardy** [comment]
Done! User is now set up in the sudo group by default.  In case you need to, it can be disabled/removed from sudo group with `--env="USER_SUDO=no"` in your `docker run` command, or if you use the docker-wine script: `./docker-wine --nosudo`

**Comment by ff4c00** [comment]
> Done! User is now set up in the sudo group by default. In case you need to, it can be disabled/removed from sudo group with `--env="USER_SUDO=no"` in your `docker run` command, or if you use the docker-wine script: `./docker-wine --nosudo`

This problem appears again in the latest version.
