### ISSUE TITLE
winetricks can't find winbind(d)

### ISSUE THREAD

**Issue by raspi** [scottyhardy/docker-wine#16]
Dockerfile installs `winbind` package correctly, but the `winbindd` is not added to `PATH` environmental variable. So if you for example try to install `winetricks adobe_diged4` the script complains about `winbindd`. If you modify `PATH` and add `/usr/sbin`, it works.

**Comment by scottyhardy** [comment]
Tested with version `0.5.0` and confirmed PATH variable set correctly.  Also successfully ran `winetricks adobe_diged4` and able to run app without any issues
