### ISSUE TITLE
can we remove 32-bit support

### ISSUE THREAD

**Issue by scottyhardy** [scottyhardy/docker-wine#21]
The `dpkg --add-architecture i386` line in `Dockerfile` significantly increases build time and size as it pulls down 32-bit versions of all packages... Need to test if wine still functions ok without it

**Comment by scottyhardy** [comment]
Simple answer is no - it is still a requirement for installing wine on ubuntu:
https://wiki.winehq.org/Ubuntu

**Comment by c-wicklein** [comment]
I think it’s also a requirement for a robust wine solution.  I’m going to try this solution as an alternative to installing wine directly on a CentOS 8 machine because this is the easiest way to support 32-bit Windows applications.
