### ISSUE TITLE
Unable to use as basis for Dockerfiles as described in documentation

### ISSUE THREAD

**Issue by jeffdougherty** [scottyhardy/docker-wine#46]
**Describe the bug**
Able to run Wine programs using the docker-wine script, but can't make my own Dockerfile to add new programs to run under Wine.

**To Reproduce**
Using the following test Dockerfile, as given on Docker Hub documentation:
FROM scottyhardy/docker-wine:latest
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["wine", "notepad.exe"]

Build image using e.g. `docker build -t docker-wine-test .`
`docker run`

See a long list of errors, which seem to indicate that there's no X server running.  See below for detailed console log.

**Expected behavior**
Should see Notepad, as when I run this with `docker-wine`

**Screenshots**
Not a screenshot, but the console dump from the failure:

[wine-console.txt](https://github.com/scottyhardy/docker-wine/files/3532537/wine-console.txt)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 18.04
- Desktop: GNOME 3.12
 - Browser Chromium 
 - Version 76.0.3809.100

**Additional context**
Able to run programs without a problem on the same machine by using docker-wine, i.e. `docker-wine wine notepad.exe`

**Comment by scottyhardy** [comment]
Hi @jeffdougherty 

What's the actual `docker run` command you're using in full?  I suspect this may be the problem as the `docker-wine` script mounts the host machine's X11 socket, the value of environment variable DISPLAY and user's Xauthority key.  I'd originally had these details in the `README.md` but removed them to reduce the sheer size of the document as there's more options for running the container now, such as with and without pulseaudio support and support for macOS.

I'm thinking I'll dedicate a separate doco with the various `docker run` commands I use and a breakdown of the other requirements for using audio, etc.

In the meantime, please try this `docker_run` command to rule out any other potential causes:
```bash
DOCKER_IMAGE="scottyhardy/docker-wine:latest"  # <--- Replace with your image name and tag

docker run -it \
--rm \
--env="DISPLAY" \
--volume="${XAUTHORITY:-${HOME}/.Xauthority}:/root/.Xauthority:ro" \
--volume="/tmp/.X11-unix:/tmp/.X11-unix:ro" \
--hostname="$(hostname)" \
$DOCKER_IMAGE wine notepad
```

**Comment by scottyhardy** [comment]
This was an old issue and not sure if I'll here back from the reporter... Basic `docker run` instructions are now included in README.md
