### ISSUE TITLE
Mac OS VNC example

### ISSUE THREAD

**Issue by brandonros** [scottyhardy/docker-wine#47]
From the README:

> There's a few different ways this problem can be solved, but essentially it comes down to using TCP sockets or a remote desktop protocol such as VNC.

How would you achieve working display through VNC on Mac OS?

**Comment by scottyhardy** [comment]
Essentially you'll need a desktop like Gnome or Xfce and a VNC server, although lately I've been seeing people using RDP and I'm considering implementing something along those lines myself
