### ISSUE TITLE
Access to host files from the docker-wine image

### ISSUE THREAD

**Issue by hlfernandez** [scottyhardy/docker-wine#53]
Hi,

First of all I want to thank you for this contribution, it is really useful.

I want to ask for guidance on how to properly share data with host. Let's say you want to run notepad (docker-wine wine notepad) and want to save your notes in a host directories rather than in the volume, which is not accessible from the host. This can be useful for other types of programs in order to manipulate user files. Typically what I would do with other Docker images is to mount a volume (e.g. `--volume=/home/user/my_data:/data`) and then access to that volume, but in this case it does not work due to user permissions since the wineuser can't access that directory. An obvious solution is to give proper permissions to that directory so that it can write in it, but I would like to ask you if there is a more elegant and general solution.

Regards,

 Hugo.

**Comment by scottyhardy** [comment]
Hi @hlfernandez 

The best solution would be to set the wineuser UID to match your own by passing your UID as an argument to the ENTRYPOINT script.  I’ll try to add this feature soon

**Comment by hlfernandez** [comment]
Thank you, please let me know when the feature is available to have a look and try it.

**Comment by scottyhardy** [comment]
Hi @hlfernandez 

I've added this feature (along with a bunch of others) to the latest build.  To give it a go, clone or pull the master branch and run the following:

```bash
./docker-wine --as-me --home-volume="${HOME}/just_testing"
```

I'm pretty confident it should just work, but please let me know if you run into any issues

**Comment by hlfernandez** [comment]
Thanks @scottyhardy, I have tried it and it seems to be working good, well done. 

By the way, the latest Docker image asked me to install wine-mono and Gecko the first time I ran it and I don't think that the previous image versions (last week) were asking to do that. Is this expected?

**Comment by scottyhardy** [comment]
Thanks for testing and feedback @hlfernandez.  As for mono and gecko, I’d removed their downloads from the docker image to reduce image size during my code overhaul, but I want a better experience when using the image so I’ll look at reintroducing them.

**Comment by scottyhardy** [comment]
The gecko and mono thing was bothering me, so I’ve fixed that now with a much better solution to ensure the latest versions download and are baked into the image without having to update any scripts - it’s available now if you’d like to give it a try

**Comment by hlfernandez** [comment]
Cool, this is much better. I think we can close this issue since you have already included the support for volumes. Thank you so much.
