### ISSUE TITLE
Support `RUN wineconsole ...` from within Dockerfile

### ISSUE THREAD

**Issue by brandonros** [scottyhardy/docker-wine#88]
I am doing something really gross. I have `.DLLs` that I want to call into from `node.js`.

```
FROM scottyhardy/docker-wine:latest
WORKDIR /app
# copy source
COPY server.js .
COPY package.json .
COPY package-lock.json .
# copy executable
COPY seed-key.exe .
COPY library.dll .
# copy win32 node
COPY node-v12.18.3-win-x86 node-v12.18.3-win-x86
# install modules
RUN wineconsole --backend=curses /app/node-v12.18.3-win-x86/node.exe /app/node-v12.18.3-win-x86/node_modules/npm/bin/npm-cli.js install
```

then in node.js

```
const express = require('express')
const execa = require('execa')
const cors = require('cors')

const app = express()
app.use(express.json())
app.post('/security-access', async (req, res) => {
  const { dll, level, seed } = req.body
  const { stdout } = await execa('seed-key.exe', [dll, level, seed])
  res.send({
    key: stdout.trim()
  })
})
app.listen(process.env.PORT || 3000, () => console.log('Listening...'))
```

wineconsole errors out hard because it is expecting some kind of... pipe or TTY or something and in the `docker build` context, that isn't possible (no stdin)

What do you recommend?

Ideally I'd like to add `ENTRYPOINT ["wineconsole", "--backend=curses", "/app/node-v12.18.3-win-x86/node.exe", "server.js"]` at the end too but it has a similar problem.

**Comment by brandonros** [comment]
For anybody else:

just add `ENV TERM='dumb'`

Fixes the `Error opening terminal: unknown.` error

**Comment by scottyhardy** [comment]
Hey, thanks for this - I’d like to think users can use this image in their CI builds or for downstream dockerfiles/images.  Using `wineconsole` still needs X11 (I thought) so you could use `ARG USE_XVFB=yes` to stop any X11 or DISPLAY type errors

**Comment by mviereck** [comment]
It is possible to access an X server over TCP during `docker build`. This helps to install Windows applications that are only possible with an interactive GUI. I've documented it here: https://github.com/mviereck/x11docker/wiki/docker-build-with-interactive-GUI
This is gross and the build is not automatically reproducible anymore, but if nothing else works, it is a possible way to go.
