### ISSUE TITLE
Local Build fails with apt-get errors 

### ISSUE THREAD

**Issue by ggkunka** [scottyhardy/docker-wine#89]
Hi @scottyhardy , First of all, I would like to thank you for this wonderful contribution.

I'm trying to build the image and facing the below error. Could you please help me out here?

Reading package lists...
E: The repository 'https://dl.winehq.org/wine-builds/ubuntu focal Release' does not have a Release file.
The command '/bin/sh -c wget -nv -O- https://dl.winehq.org/wine-builds/winehq.key | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 apt-key add -     && apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu/ $(grep VERSION_CODENAME= /etc/os-release | cut -d= -f2) main"     && dpkg --add-architecture i386     && apt-get update     && DEBIAN_FRONTEND="noninteractive" apt-get install -y --install-recommends winehq-${WINE_BRANCH}     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
[root@localhost docker-wine-master]#

Complete log is here
[build_error.txt](https://github.com/scottyhardy/docker-wine/files/4999931/build_error.txt)

**Comment by scottyhardy** [comment]
Seems to be an issue with your proxy:
`Err:3 https://dl.winehq.org/wine-builds/ubuntu focal Release
  Could not handshake: Error in the pull function. [IP: 10.158.100.6 8080]`

Maybe just test without the proxy?

**Comment by ggkunka** [comment]
Thank you.
I tried on my personal laptop and it worked just fine. 
It does seem like an issue with proxy at my workplace.

**Comment by ggkunka** [comment]
Hi @scottyhardy ,

I have another query.
How do we build a docker image with pre-installed windows software? Is there a way to do this via Dockerfile?

Thanks

**Comment by scottyhardy** [comment]
A very good question @ggkunka and something I’ve wanted to explore/document.  I’ll make this a new issue
