### ISSUE TITLE
Last update prevents installing certain dlls

### ISSUE THREAD

**Issue by TheLamia** [scottyhardy/docker-wine#92]
I have used the image couple of months ago to run a Windows program which required some DLL and fonts that I had to install through winetricks. It went fine at that time but for some issues, the image crashed and I had to create a new volume and redo the installation. This time when I tried with the new updated image I was not able to install the dependencies, I got a winetricks warning regarding the wine prefix and architecture: 
_

> You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.

_
 which I changed to 32 bit hoping it would fix the issue. However, every time I try to install the dlls (mdac 28 , or 27) I get the following message: 

>  Extracting file failed. It is most likely caused by low memory or corrupted Cabinet file.

This error is due to running mdac_typ.exe. I am curious to know what changes were made to the image to help me find the issue and fix it?

**Comment by scottyhardy** [comment]
Hi @TheLamia - thanks for reporting this issue. I’m not sure why but the problem relates to using Ubuntu 20.04 focal for the base image as it doesn’t exist in earlier OS versions (found solution in https://github.com/Winetricks/winetricks/issues/1525 and also same error as yours in https://github.com/Winetricks/winetricks/issues/1543).

The problem only seems to occur in docker - an Ubuntu Focal VM does not have any issues when tested.  There’s probably a difference in the wine dependencies installed between versions but haven’t investigated any further yet.  For now, I’ll be using Ubuntu 19.10 eoan for the base as a workaround.
