### ISSUE TITLE
Sources to install (missing) packages 

### ISSUE THREAD

**Issue by kaleming** [scottyhardy/docker-wine#98]
Hi, I need to install some programs using the terminal. Some requires root privileges, but many packages are not available and it's a bit trick to install.

**To Reproduce**

1-Run `./docker-wine --as-root`

2- Run `su -`

3- `apt-get install sudo -y`

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package sudo is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

**Desktop :**
 - OS:Ubuntu 18.04

**Comment by bertou** [comment]
eon is End Of Life and not supported anymore.
I could install new packages (compiler, make, vim) using old-releases:
en un ./docker-wine --as-root:
cp /etc/apt/sources.list /etc/apt/sources.list.bak
cat /etc/apt/sources.list.bak | grep -v "#" | sed 's/archive/old-releases/'
apt update
apt install ...

**Comment by johncadengo** [comment]
@scottyhardy any chance we can get a different version of the Ubuntu image working with this? It seems 19.10, Eoan, is EOL. I can't seem to get anything installed using apt, even when I manage to get into the container as root.

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
```

**Comment by scottyhardy** [comment]
Hi @kaleming @johncadengo @bertou this issue is resolved now.  Builds are currently using Ubuntu 20.04 focal and I’ll only use LTS versions from now
